### ISSUE TITLE
persp-projectile isn't available in melpa stable anymore

### ISSUE THREAD

**Issue by favadi** [bbatsov/persp-projectile#2]
I guess it happens after splitting the repo.

**Comment by favadi** [comment]
This issue can be resolved by tag a release, right?

**Comment by tejasbubane** [comment]
I can see `persp-projectile` after doing `package-list-packages`.

```
persp-projectile   20151220.430  installed             Perspective integration with Projectile
```

Also it seems to be available in melpa:

![screen shot 2016-02-26 at 1 13 46 am](https://cloud.githubusercontent.com/assets/980783/13332067/48aad30e-dc26-11e5-9f19-d2a9fee1e557.png)

**Comment by favadi** [comment]
> Also it seems to be available in melpa:

This issue is about melpa stable.

**Comment by DamienCassou** [comment]
Could you please tag the current commit so that the package appears on melpa stable? You can do it through github in the "releases" tab or through `git tag`. Thanks

**Comment by favadi** [comment]
@bbatsov same problem as https://github.com/bbatsov/helm-projectile/issues/11.

**Comment by favadi** [comment]
There is a tag now, closing.
