### ISSUE TITLE
The project needs a new version number for Melpa...

### ISSUE THREAD

**Issue by WJCFerguson** [bbatsov/persp-projectile#22]
At least I think that's the problem.  I pull from melpa-stable by default, and get version 0.2.0, which doesn't work on Emacs 26 (specifically, it's missing b937efac9f).  I think, assuming it's appropriate, if you increment the version number, then people installing melpa stable will be able to use this package.

(unless I've got the wrong end of the stick somewhere).

Thanks!

**Comment by bbatsov** [comment]
Done.
