### ISSUE TITLE
Package-Requires update

### ISSUE THREAD

**Issue by csantosb** [bbatsov/persp-projectile#27]
Hi,

Could you please update the package-requires ? This blocks proper package upgrade.
At least, perspective "2.16" and projectile "2.5" are necessary.

Thanks,

**Comment by bbatsov** [comment]
I can update them, but I'm not sure why would they be needed. I don't think this package uses any newer features from both packages.

**Comment by csantosb** [comment]
The thing is that, when using guix as an emacs packages manager, upgrading projectile to 2.5 blocks because of the dependency of persp-projectile on projectile 2.4.

![upgrade](https://user-images.githubusercontent.com/5930297/129593148-81e861d6-8cfb-4036-bf7a-6055b34038d1.png)

**Comment by csantosb** [comment]
That being said, I just realized that the requirements are minimum versions, not mandatory versions, as I'm currently using perspective 2.16 without upgrading issues. There must be a quirck at the guix side, sorry.
