### ISSUE TITLE
latest projectile has broken the package

### ISSUE THREAD

**Issue by ambihelical** [bbatsov/persp-projectile#5]
projectile-persp-switch-project generates error "wrong type argument:  stringp,nil" after project is selected. 

Possilbly changes to projectile-completing-read pushed Oct 5 2016 are causing this, but I'm not experienced enough with elisp to diagnose it.

**Comment by featalion** [comment]
I have the same error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  directory-file-name(nil)
  projectile-persp-switch-project(nil)
  funcall-interactively(projectile-persp-switch-project nil)
  call-interactively(projectile-persp-switch-project nil nil)
  command-execute(projectile-persp-switch-project)
```

Emacs 25.1.

**Comment by featalion** [comment]
I debug a few and found, that `projectile-completing-read` function returns `nil` on <Ret> from Helm buffer. [Line 1596](https://github.com/bbatsov/projectile/blob/master/projectile.el#L1596):

```
(helm :sources
      `((name . ,prompt)
        (candidates . ,choices)
        (action . ,(prog1 action
                     (setq action nil)))))
```
